version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - /PluginSamples/ImageStore/ImageStore
      - /PluginSamples/ScratchFilter/ScratchFilter
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
