version: 2
updates:
  - package-ecosystem: nuget
    directory: /PluginSamples/ImageStore/ImageStore
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
  - package-ecosystem: nuget
    directory: /PluginSamples/ScratchFilter/ScratchFilter
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
