//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchFilter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchFilter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Disable scratch filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar_ScratchFilter_Description_Active {
            get {
                return ResourceManager.GetString("Toolbar.ScratchFilter.Description.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable scratch filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar_ScratchFilter_Description_Inactive {
            get {
                return ResourceManager.GetString("Toolbar.ScratchFilter.Description.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scratch filter settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar_ScratchFilterSetting_Description {
            get {
                return ResourceManager.GetString("Toolbar.ScratchFilterSetting.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Toolbar_ScratchFilterSetting_Icon_Dark {
            get {
                object obj = ResourceManager.GetObject("Toolbar.ScratchFilterSetting.Icon.Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Toolbar_ScratchFilterSetting_Icon_Light {
            get {
                object obj = ResourceManager.GetObject("Toolbar.ScratchFilterSetting.Icon.Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar_ScratchFilterSetting_Label_Cancel {
            get {
                return ResourceManager.GetString("Toolbar.ScratchFilterSetting.Label.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image brightness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar_ScratchFilterSetting_Label_ImageBrightness {
            get {
                return ResourceManager.GetString("Toolbar.ScratchFilterSetting.Label.ImageBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image contrast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar_ScratchFilterSetting_Label_ImageContrast {
            get {
                return ResourceManager.GetString("Toolbar.ScratchFilterSetting.Label.ImageContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image gamma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar_ScratchFilterSetting_Label_ImageGamma {
            get {
                return ResourceManager.GetString("Toolbar.ScratchFilterSetting.Label.ImageGamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image saturation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar_ScratchFilterSetting_Label_ImageSaturation {
            get {
                return ResourceManager.GetString("Toolbar.ScratchFilterSetting.Label.ImageSaturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toolbar_ScratchFilterSetting_Label_OK {
            get {
                return ResourceManager.GetString("Toolbar.ScratchFilterSetting.Label.OK", resourceCulture);
            }
        }
    }
}
